### ISSUE TITLE
Fetch question dynamically and place the input in slot 

### ISSUE THREAD

**Issue by Jinay09** [RasaHQ/rasa-form-examples#3]
RASA version 2.3.1
Python version 3.8.5
RASA sad version 2.3.1

I want to ask user questions in the chatbot dynamically. 
so, basically, I already have questions stored inside the database and I am fetching those questions in an action file and after that, I want to start form. that question's answers will be stored in a particular slot. 
so, whenever I add one more question inside the database it will ask in the chatbot.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Hi @Jinay09. 

This sounds like a general Rasa question instead of a question related to this repository, am I correct? 

If so, could you post the question on our forum instead? https://forum.rasa.com

**Comment by Jinay09** [comment]
Thank you for your reply.
Yes, can guide me on how to ask on https://forum.rasa.com
I tried but wasn't able to ask.

**Comment by koaning** [comment]
You first need to sign up and make an account, did that not work for you?
