### ISSUE TITLE
Necessary to explicitly name action?

### ISSUE THREAD

**Issue by ankandrew** [RasaHQ/rasa-form-examples#4]
Is it necessary in [this line](https://github.com/RasaHQ/rasa-form-examples/blob/964a100fd301903d75789a1e5f484fd5dad73b06/03-simple-form/domain.yml#L42) to inlude `utter_greet` under `actions` if `utter_greet` is already included in `responses`? Doubt arises when reading [this](https://rasa.com/docs/rasa/domain/#actions) from docs.

**Comment by koaning** [comment]
I don't consciously remember adding it and I wonder if this was added automatically by running `rasa interactive`.
